### ISSUE TITLE
ShowNode has Target set to TargetComp

### ISSUE THREAD

**Issue by mirza-afk** [AutumnRivers/hacknet-vscode#1]
The example given in the guide for the ShowComp action is
`<ShowNode DelayHost="advExamplePC" Delay="21.5" Target="advExamplePC" />`
However this extension's autocomplete (I think that's what you call it?) sets `Target` to `TargetComp`, making Hacknet get confused and not recognize it as the target being referenced.
Sorry if I'm being pedantic, but I got an error in my extension and this was the culprit.
Otherwise this is a great extension and makes my extension development significantly quicker.

**Comment by AutumnRivers** [comment]
Fixed in https://github.com/AutumnRivers/hacknet-vscode/commit/5008f2d6c71069a0fe51fb83455c19fb20b1caf6
