### ISSUE TITLE
goal type="uploadfile" should be changed to "fileupload"

### ISSUE THREAD

**Issue by MXYLR** [AutumnRivers/hacknet-vscode#3]
<goal type="uploadfile" target="nodeID" file="uploadme.dec" path="home" destTarget="dropNodeID" destPath="Drop" decrypt="true" decryptPass="password"/>

**Comment by AutumnRivers** [comment]
Fixed in https://github.com/AutumnRivers/hacknet-vscode/commit/5008f2d6c71069a0fe51fb83455c19fb20b1caf6
